name: Java CI

on: [push]

jobs:
  build:
    name : Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checks-out the repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v1
    - name: Build with Maven
      run: mvn compile
