name: Java CI

on: [push]

jobs:
  build:
    name : Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checks-out the repository under $GITHUB_WORKSPACE
      uses: actions/checkout@v1
    - name: Build with Maven
      run: mvn compile --file pom.xml
  
  tests_j8 :
    needs: [build]
    name: Tests in Java 8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Test with Maven
      run: mvn test --file pom.xml
   
  tests_j11 :
    needs: [build]
    name: Tests in Java 11
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Test with Maven
      run: mvn test --file pom.xml
  
  
  deploy:
    needs: [tests_j8, tests_j11]
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        java-version: 11
    #- name: Deploy Javadoc
      #run: mvn -B javadoc:javadoc --file pom.xml
    - name: Build with maven
      run: mvn clean verify --file pom.xml
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: target/project-0.0.1-SNAPSHOT.jar
      
